Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ex2_path = Path('example2-reduced')

dark_90 = CCDData.read(ex2_path / 'combined_dark_90.000.fit')
dark_1000 = CCDData.read('combined_dark_exposure_1000.0.fit.bz2')
dark_1000 = ccdp.trim_image(dark_1000[:, :4096])

dark_90 = dark_90.multiply(1.5 * u.electron / u.adu).divide(90 * u.second)
dark_1000 = dark_1000.multiply(1.5 * u.electron / u.adu).divide(1000 * u.second)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_4189/805464159.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mdark_90[0m [0;34m=[0m [0mCCDData[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mex2_path[0m [0;34m/[0m [0;34m'combined_dark_90.000.fit'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mdark_1000[0m [0;34m=[0m [0mCCDData[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m'combined_dark_exposure_1000.0.fit.bz2'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mdark_1000[0m [0;34m=[0m [0mccdp[0m[0;34m.[0m[0mtrim_image[0m[0;34m([0m[0mdark_1000[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m:[0m[0;36m4096[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/nddata/mixins/ndio.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m     56[0m [0;34m[0m[0m
[1;32m     57[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 58[0;31m         [0;32mreturn[0m [0mregistry[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_cls[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m [0;34m[0m[0m
[1;32m     60[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/io/registry.py[0m in [0;36mread[0;34m(cls, format, cache, *args, **kwargs)[0m
[1;32m    510[0m                     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    511[0m                         [0mctx[0m [0;34m=[0m [0mget_readable_fileobj[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m'binary'[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 512[0;31m                         [0mfileobj[0m [0;34m=[0m [0mctx[0m[0;34m.[0m[0m__enter__[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    513[0m                     [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    514[0m                         [0;32mraise[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.8/contextlib.py[0m in [0;36m__enter__[0;34m(self)[0m
[1;32m    111[0m         [0;32mdel[0m [0mself[0m[0;34m.[0m[0margs[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mkwds[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mfunc[0m[0;34m[0m[0;34m[0m[0m
[1;32m    112[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 113[0;31m             [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgen[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m         [0;32mexcept[0m [0mStopIteration[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m             [0;32mraise[0m [0mRuntimeError[0m[0;34m([0m[0;34m"generator didn't yield"[0m[0;34m)[0m [0;32mfrom[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/utils/data.py[0m in [0;36mget_readable_fileobj[0;34m(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers)[0m
[1;32m    260[0m                 [0mtimeout[0m[0;34m=[0m[0mremote_timeout[0m[0;34m,[0m [0msources[0m[0;34m=[0m[0msources[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    261[0m                 http_headers=http_headers)
[0;32m--> 262[0;31m         [0mfileobj[0m [0;34m=[0m [0mio[0m[0;34m.[0m[0mFileIO[0m[0;34m([0m[0mname_or_obj[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    263[0m         [0;32mif[0m [0mis_url[0m [0;32mand[0m [0;32mnot[0m [0mcache[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    264[0m             [0mdelete_fds[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mfileobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'combined_dark_exposure_1000.0.fit.bz2'
FileNotFoundError: [Errno 2] No such file or directory: 'combined_dark_exposure_1000.0.fit.bz2'

